export enum ApplicationError {
  // Erros de usuário
  USER_NOT_FOUND = "USER_NOT_FOUND",
  USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS",
  INVALID_USER_CREDENTIALS = "INVALID_USER_CREDENTIALS",
  INVALID_USER_DATA = "INVALID_USER_DATA",

  // Erros de clínica
  CLINIC_NOT_FOUND = "CLINIC_NOT_FOUND",
  CLINIC_ALREADY_EXISTS = "CLINIC_ALREADY_EXISTS",
  INVALID_CLINIC_DATA = "INVALID_CLINIC_DATA",

  // Erros de oferta de exame
  EXAM_OFFER_NOT_FOUND = "EXAM_OFFER_NOT_FOUND",
  EXAM_OFFER_ALREADY_EXISTS = "EXAM_OFFER_ALREADY_EXISTS",
  INVALID_EXAM_OFFER_DATA = "INVALID_EXAM_OFFER_DATA",

  // Erros de hospital
  HOSPITAL_NOT_FOUND = "HOSPITAL_NOT_FOUND",
  HOSPITAL_ALREADY_EXISTS = "HOSPITAL_ALREADY_EXISTS",
  INVALID_HOSPITAL_DATA = "INVALID_HOSPITAL_DATA",

  // Erros de contratos de oferta
  OFFER_CONTRACT_NOT_FOUND = "OFFER_CONTRACT_NOT_FOUND",
  OFFER_CONTRACT_ALREADY_EXISTS = "OFFER_CONTRACT_ALREADY_EXISTS",
  INVALID_OFFER_CONTRACT_DATA = "INVALID_OFFER_CONTRACT_DATA",

  // Erros de exames médicos
  MEDICAL_EXAM_NOT_FOUND = "MEDICAL_EXAM_NOT_FOUND",
  MEDICAL_EXAM_ALREADY_EXISTS = "MEDICAL_EXAM_ALREADY_EXISTS",
  INVALID_MEDICAL_EXAM_DATA = "INVALID_MEDICAL_EXAM_DATA",

  // Erros genéricos
  DATABASE_ERROR = "DATABASE_ERROR",
  INVALID_REQUEST = "INVALID_REQUEST",
  PERMISSION_DENIED = "PERMISSION_DENIED",

  //API ERROR
  ERROR_FETCHING_DATA_FROM_API = "ERROR_FETCHING_DATA_FROM_API",
}
